language: node_js
node_js:
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "Z/w/2rE6vPy6EvYxuLMKiVXEidGLYMnsL2PAwdUKr7F3pR8UBc9KCAKk36/pD2DBgm/mpIEWz6YQ0paCdqQPAyZ/K5BYJxeXYotH9GdI8IL0rd370DNbxo1WPzz9a++JP8jweSAqGMXd26GXN4e9Rrz/dVFUrggn+FFuJvvIVNsxkEwf8XN5wBSpEexWY0nEso+CegM+hWZcE2MEsNDIfMHVfNHlDc6YLp4atpfVv6915HL4XCSLqedeygHYe689Cu15YoFENxFat9JyyyjHgypUzl8Xd0fp97i4X+swoGiXnICAGya51JJr5SC7a7On7gdcxm57IlhjeQYKyQumKU/qWri5kMhV1FuPR9GYtT2h9NsqIBMNxGo5rVgLLzpW7GT1be/qLoiS/7LGnYvZEodkQ+vE/+lD0/KfRyBqIN/qCaARnLodXiVGEL7WzvJelhBQ3UqJDslhxRaifAfI2KUdoV1CwWj5m3uAIUeQpShzKDuXWx+EMs7qqopSqLZDwPqXJQcz2NCcar9mcF8AkIAK4xLMMiEjsLVNYC4yC3mgDAEpQq+qS9dL38Mdjs7ha72HVukAQ2dryxQEPdQgdNBf2Dz7c/QbPjjocKnU++3FbUXiu3GUgb6+uKZcUZqfJZPTk09VHL8PNZ1wSTBuSn4A18D+8QOaUYGMvR4qjZ0="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "Z/w/2rE6vPy6EvYxuLMKiVXEidGLYMnsL2PAwdUKr7F3pR8UBc9KCAKk36/pD2DBgm/mpIEWz6YQ0paCdqQPAyZ/K5BYJxeXYotH9GdI8IL0rd370DNbxo1WPzz9a++JP8jweSAqGMXd26GXN4e9Rrz/dVFUrggn+FFuJvvIVNsxkEwf8XN5wBSpEexWY0nEso+CegM+hWZcE2MEsNDIfMHVfNHlDc6YLp4atpfVv6915HL4XCSLqedeygHYe689Cu15YoFENxFat9JyyyjHgypUzl8Xd0fp97i4X+swoGiXnICAGya51JJr5SC7a7On7gdcxm57IlhjeQYKyQumKU/qWri5kMhV1FuPR9GYtT2h9NsqIBMNxGo5rVgLLzpW7GT1be/qLoiS/7LGnYvZEodkQ+vE/+lD0/KfRyBqIN/qCaARnLodXiVGEL7WzvJelhBQ3UqJDslhxRaifAfI2KUdoV1CwWj5m3uAIUeQpShzKDuXWx+EMs7qqopSqLZDwPqXJQcz2NCcar9mcF8AkIAK4xLMMiEjsLVNYC4yC3mgDAEpQq+qS9dL38Mdjs7ha72HVukAQ2dryxQEPdQgdNBf2Dz7c/QbPjjocKnU++3FbUXiu3GUgb6+uKZcUZqfJZPTk09VHL8PNZ1wSTBuSn4A18D+8QOaUYGMvR4qjZ0="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "yv/KsT9huQYt1kbS7krFiohRKAKn6iq/4blDUuz9na2l0MtvlqCAZ2XZaxJuO+ACTIH/2xbF4MsVT7ldae2CFAXxYfu+cv2ogeBM3YawQdTTa2B7gDBCZWx0nQZVla1J/F7slj+rr9q19GrCZr8SGpqBKWcRJOxPeDEDZ3iFacffmPY09EoeVXtVCM8FcxtLcX1gRqtwfYWi/VmoB9riraT0zFCuCKcwddYV1Wuym+wzKGQ6zTbD+nHGojCtDHeBmlKhBYLEviBSQla8F78Vx2N5ho6GsN9QrakgIAVMai9OIagvo3LNbbZt8oiZjoXO9BJScsStARRB/9DPt7EJczl2pGR+oMG+l1/9Tsv2ZS72dHuj8z2JctRDWqdu9sjWwfTTriCVdarQAMbVMszPq7/WwcqXezKdOM/VnpTWYoZFEBraTfBp2a0tQPFhxeI3bDhnBmWMMDsp9aK1wO6DEJona/uFWrRjcw9HEO4SHhDDLv1Km9AphB6mfdInjQp67wEIvSKUFvWNiD91rPl6RZGCkKfC+mVsrEa0Uoc67jAibaJhdeHi7xY406/yXE0BLShkXxwf7OI9xbFZ9+njsdReJyX9Hp2Xq4bpT/PGN2luHGXgFFL3M+6ZPVSSDqf/W6SiPysAh+X7/iV3apLRMHgklUMNZ+nsrHhgWfG6Cv4="
    on:
      tags: true
    skip_cleanup: true
